name: CI

# Controls when the action will run.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  type-check:
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so it can be accessed
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.10.4
      - name: Start the linter
        run: |
          pnpm install
          pnpm run test